version: '3.8'

services:
    web:
        build:
            context: .
            target: dev
        links: 
            - mongodb
        env_file:
            - ./config/dev.env
        ports:
            - "3000:3000"

    mongodb:
        image: mongo:5.0.6
        container_name: mongodb
        volumes: 
            - /var/mongo/data:/data

